export const ADD_TODO = "ADD_TODO";
export const REMOVE_FROM_TODO = "REMOVE_FROM_TODO";
export const COMPLETE_ITEM = "COMPLETE_ITEM";
export const GET_TODO_ITEMS = "GET_TODO_ITEMS";
export const BRANDS_FETCH_FAIL = "BRANDS_FETCH_FAIL";
